### PR TITLE
Logo offer Offline Translator

### PR DESCRIPTION
**Pull request by familqasimov**
Hi sir. I'm graphic designer. I have studied your work and I think a new design will make you more visible. I would like to offer logo. I can give you all the formats of the design free. If you want a change please specify.

Best regards 
Famil.

### CODE REVIEW

**Comment by no-go** [comment]
Hi Famil,
my translator app is still under contruction, thus it is a good idea to add/change the logo at this part of the project. Because my project is with a http://unlicense.org license, to logo has to be the same license.

Is your logo license free? Can I use it without any copyright issues? Am I free to change it a bit?

Best regards
Jochen.

PS: in the last 4 days I got a lot of logo offers. That is realy strange. I am not sure that this is serious. I identify many new accounts with very similar content in issues about "free logo". I was unsure to report all of these users (you too!) but I think, you are not a bot and your logo offer seams to be serious.

**Comment by familqasimov** [comment]
Yes my brother. You can use with great pleasure.  If you like it I sent you
PR

18 may 2018, Cümə 11:34 tarixində Jochen Peters <notifications@github.com>
yazdı:

**Comment by no-go** [comment]
:-) but what does PR mean? I am a single man without a PR-Agency :-D

**Comment by familqasimov** [comment]
😊 Pull Reguest my brother.
 I fork your project and load all logo files. Then you merge it yourself.

18 may 2018, Cümə 11:41 tarixində Jochen Peters <notifications@github.com>
yazdı:

**Comment by no-go** [comment]
😀👍

**Comment by familqasimov** [comment]
Please. If you like this logo merge it.

Best Regards
Famil.

**Comment by no-go** [comment]
I have to download, check the files and then I may merge it. png files could be content strange stuff. please give me some days

**Comment by no-go** [comment]
Thanks for your work. I will add a modified version of the logo in my next version :-D

**Pull request closed without merging**
